/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GuardianRegistry } from "./GuardianRegistry";
export type { IdentityRegistry } from "./IdentityRegistry";
