export const env = {
  OPENAI_API_KEY: process.env.OPENAI_API_KEY ?? "",
  ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY ?? "",
  PRIVY_APP_ID: process.env.NEXT_PUBLIC_PRIVY_APP_ID ?? "",
  PRIVY_APP_SECRET: process.env.PRIVY_APP_SECRET ?? "",
  SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL ?? "",
  SUPABASE_KEY: process.env.NEXT_PUBLIC_SUPABASE_KEY ?? "",
  SUPABASE_SECRET_KEY: process.env.NEXT_SUPABASE_SECRET_KEY ?? "",
  BACKEND_URL: process.env.NEXT_PUBLIC_BACKEND_URL ?? "http://localhost:3001",
  RPC_URL: process.env.NEXT_PUBLIC_RPC_URL ?? "",
  CHAIN_ID: Number(process.env.NEXT_PUBLIC_CHAIN_ID ?? "21668"),
  DEPLOYER_PRIVATE_KEY: process.env.DEPLOYER_PRIVATE_KEY ?? "",
  DEPLOYER_ADDRESS:
    process.env.NEXT_PUBLIC_DEPLOYER_ADDRESS ??
    "0x8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC",
  IDENTITY_REGISTRY_ADDRESS:
    process.env.NEXT_PUBLIC_IDENTITY_REGISTRY_ADDRESS ??
    "0x68EA48917a3f9416613A48788BCe54578395a315",
  GUARDIAN_REGISTRY_ADDRESS:
    process.env.NEXT_PUBLIC_GUARDIAN_REGISTRY_ADDRESS ??
    "0xE742a4b5F98453027fA3A9b0de106e237B6746B1",
  PERMISSION_MANAGER_ADDRESS:
    process.env.NEXT_PUBLIC_PERMISSION_MANAGER_ADDRESS ??
    "0xb91b7959e715c059cE10eBEbe3288dA9d8012961",
  CLINICAL_EPISODE_REGISTRY_ADDRESS:
    process.env.NEXT_PUBLIC_CLINICAL_EPISODE_REGISTRY_ADDRESS ??
    "0x207Ac23cf698ce54ad2AE2391be5df4b8c66430F",
  MEDICAL_ORDER_REGISTRY_ADDRESS:
    process.env.NEXT_PUBLIC_MEDICAL_ORDER_REGISTRY_ADDRESS ??
    "0x9E1222D98DBc740bbD406b5945084D363888CeA0",
  MEDICAL_DOCUMENT_REGISTRY_ADDRESS:
    process.env.NEXT_PUBLIC_MEDICAL_DOCUMENT_REGISTRY_ADDRESS ??
    "0x5b190A85fb41D7C1d173a4501f12b81c28F59824",
  HEALTHCARE_NETWORK_REGISTRY_ADDRESS:
    process.env.NEXT_PUBLIC_HEALTHCARE_NETWORK_REGISTRY_ADDRESS ??
    "0x724820e539ae50f5fe7434fc9a6Cd2B17F832D31",
  AUDIT_TRAIL_ADDRESS:
    process.env.NEXT_PUBLIC_AUDIT_TRAIL_ADDRESS ??
    "0x1AA001Cd20F35F3F4EF1A945053CeE4Acc24aDb4",
  EMERGENCY_ACCESS_MANAGER_ADDRESS:
    process.env.NEXT_PUBLIC_EMERGENCY_ACCESS_MANAGER_ADDRESS ?? "",
  HEALTH_PROOF_KERNEL_ADDRESS:
    process.env.NEXT_PUBLIC_HEALTH_PROOF_KERNEL_ADDRESS ??
    "0xcad00692aa206527F64Fc683dB0f711dc49CB176",
  HEALTH_PROOF_GATEWAY_ADDRESS:
    process.env.NEXT_PUBLIC_HEALTH_PROOF_GATEWAY_ADDRESS ??
    "0xe820D68E02Dd7D82f73b3B5E20732C09DE7829DA",
  HEALTH_PROOF_PROTOCOL_ADDRESS:
    process.env.NEXT_PUBLIC_HEALTH_PROOF_PROTOCOL_ADDRESS ??
    "0x0D6F31D23704631417D8C55360aF2D493A578BF2",
  PINATA_JWT: process.env.PINATA_JWT_SECRET ?? "",
  PINATA_GATEWAY: (() => {
    const gw = process.env.NEXT_PUBLIC_PINATA_GATEWAY ?? "gateway.pinata.cloud";
    return gw.startsWith("http") ? gw : `https://${gw}`;
  })(),
  ENABLE_LOCAL_OCR_ONLY:
    process.env.NEXT_PUBLIC_ENABLE_LOCAL_OCR_ONLY === "true",
  PDF_WORKER_PATH:
    process.env.NEXT_PUBLIC_PDF_WORKER_PATH ?? "/pdf.worker.min.mjs",
  TESSERACT_LANG_PATH: process.env.NEXT_PUBLIC_TESSERACT_LANG_PATH,
  TESSERACT_WORKER_PATH: process.env.NEXT_PUBLIC_TESSERACT_WORKER_PATH,
  TESSERACT_CORE_PATH: process.env.NEXT_PUBLIC_TESSERACT_CORE_PATH,
  LOINC_FHIR_BASE_URL:
    process.env.LOINC_FHIR_BASE_URL ?? "https://fhir.loinc.org",
  LOINC_SEARCH_BASE_URL:
    process.env.LOINC_SEARCH_BASE_URL ??
    "https://loinc.regenstrief.org/searchapi",
} as const;
