/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EmergencyAccessManager } from "./EmergencyAccessManager";
export type { PermissionManager } from "./PermissionManager";
