/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface HealthcareNetworkRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "createNetwork"
      | "institutions"
      | "isVerifiedInstitution"
      | "networks"
      | "registerInstitution"
      | "verifyInstitution"
      | "walletToInstitution"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "HealthcareNetworkCreated"
      | "InstitutionRegistered"
      | "InstitutionVerified"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createNetwork",
    values: [BytesLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "institutions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerifiedInstitution",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "networks", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "registerInstitution",
    values: [BytesLike, BytesLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyInstitution",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "walletToInstitution",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createNetwork",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "institutions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isVerifiedInstitution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "networks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerInstitution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyInstitution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "walletToInstitution",
    data: BytesLike
  ): Result;
}

export namespace HealthcareNetworkCreatedEvent {
  export type InputTuple = [
    networkId: BytesLike,
    name: string,
    countryCode: string,
    authority: AddressLike
  ];
  export type OutputTuple = [
    networkId: string,
    name: string,
    countryCode: string,
    authority: string
  ];
  export interface OutputObject {
    networkId: string;
    name: string;
    countryCode: string;
    authority: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InstitutionRegisteredEvent {
  export type InputTuple = [
    institutionId: BytesLike,
    networkId: BytesLike,
    wallet: AddressLike,
    institutionType: BigNumberish
  ];
  export type OutputTuple = [
    institutionId: string,
    networkId: string,
    wallet: string,
    institutionType: bigint
  ];
  export interface OutputObject {
    institutionId: string;
    networkId: string;
    wallet: string;
    institutionType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InstitutionVerifiedEvent {
  export type InputTuple = [institutionId: BytesLike];
  export type OutputTuple = [institutionId: string];
  export interface OutputObject {
    institutionId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HealthcareNetworkRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): HealthcareNetworkRegistry;
  waitForDeployment(): Promise<this>;

  interface: HealthcareNetworkRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  createNetwork: TypedContractMethod<
    [networkId: BytesLike, name: string, countryCode: string],
    [void],
    "nonpayable"
  >;

  institutions: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, string, boolean] & {
        institutionId: string;
        networkId: string;
        wallet: string;
        institutionType: bigint;
        countryCode: string;
        verified: boolean;
      }
    ],
    "view"
  >;

  isVerifiedInstitution: TypedContractMethod<
    [wallet: AddressLike],
    [boolean],
    "view"
  >;

  networks: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, boolean] & {
        networkId: string;
        name: string;
        countryCode: string;
        authority: string;
        active: boolean;
      }
    ],
    "view"
  >;

  registerInstitution: TypedContractMethod<
    [
      institutionId: BytesLike,
      networkId: BytesLike,
      wallet: AddressLike,
      institutionType: BigNumberish,
      countryCode: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  verifyInstitution: TypedContractMethod<
    [institutionId: BytesLike],
    [void],
    "nonpayable"
  >;

  walletToInstitution: TypedContractMethod<
    [arg0: AddressLike],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createNetwork"
  ): TypedContractMethod<
    [networkId: BytesLike, name: string, countryCode: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "institutions"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, string, boolean] & {
        institutionId: string;
        networkId: string;
        wallet: string;
        institutionType: bigint;
        countryCode: string;
        verified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isVerifiedInstitution"
  ): TypedContractMethod<[wallet: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "networks"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, boolean] & {
        networkId: string;
        name: string;
        countryCode: string;
        authority: string;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerInstitution"
  ): TypedContractMethod<
    [
      institutionId: BytesLike,
      networkId: BytesLike,
      wallet: AddressLike,
      institutionType: BigNumberish,
      countryCode: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyInstitution"
  ): TypedContractMethod<[institutionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "walletToInstitution"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getEvent(
    key: "HealthcareNetworkCreated"
  ): TypedContractEvent<
    HealthcareNetworkCreatedEvent.InputTuple,
    HealthcareNetworkCreatedEvent.OutputTuple,
    HealthcareNetworkCreatedEvent.OutputObject
  >;
  getEvent(
    key: "InstitutionRegistered"
  ): TypedContractEvent<
    InstitutionRegisteredEvent.InputTuple,
    InstitutionRegisteredEvent.OutputTuple,
    InstitutionRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "InstitutionVerified"
  ): TypedContractEvent<
    InstitutionVerifiedEvent.InputTuple,
    InstitutionVerifiedEvent.OutputTuple,
    InstitutionVerifiedEvent.OutputObject
  >;

  filters: {
    "HealthcareNetworkCreated(bytes32,string,string,address)": TypedContractEvent<
      HealthcareNetworkCreatedEvent.InputTuple,
      HealthcareNetworkCreatedEvent.OutputTuple,
      HealthcareNetworkCreatedEvent.OutputObject
    >;
    HealthcareNetworkCreated: TypedContractEvent<
      HealthcareNetworkCreatedEvent.InputTuple,
      HealthcareNetworkCreatedEvent.OutputTuple,
      HealthcareNetworkCreatedEvent.OutputObject
    >;

    "InstitutionRegistered(bytes32,bytes32,address,uint8)": TypedContractEvent<
      InstitutionRegisteredEvent.InputTuple,
      InstitutionRegisteredEvent.OutputTuple,
      InstitutionRegisteredEvent.OutputObject
    >;
    InstitutionRegistered: TypedContractEvent<
      InstitutionRegisteredEvent.InputTuple,
      InstitutionRegisteredEvent.OutputTuple,
      InstitutionRegisteredEvent.OutputObject
    >;

    "InstitutionVerified(bytes32)": TypedContractEvent<
      InstitutionVerifiedEvent.InputTuple,
      InstitutionVerifiedEvent.OutputTuple,
      InstitutionVerifiedEvent.OutputObject
    >;
    InstitutionVerified: TypedContractEvent<
      InstitutionVerifiedEvent.InputTuple,
      InstitutionVerifiedEvent.OutputTuple,
      InstitutionVerifiedEvent.OutputObject
    >;
  };
}
