/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GuardianRegistry__factory } from "./GuardianRegistry__factory";
export { IdentityRegistry__factory } from "./IdentityRegistry__factory";
