/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IMedicalDocumentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getMetadataHash"
      | "registerDocument"
      | "revokeDocument"
      | "verifyDocument"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getMetadataHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerDocument",
    values: [BytesLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeDocument",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDocument",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getMetadataHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDocument",
    data: BytesLike
  ): Result;
}

export interface IMedicalDocumentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IMedicalDocumentRegistry;
  waitForDeployment(): Promise<this>;

  interface: IMedicalDocumentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getMetadataHash: TypedContractMethod<
    [documentHash: BytesLike],
    [string],
    "view"
  >;

  registerDocument: TypedContractMethod<
    [documentHash: BytesLike, issuer: AddressLike, metadataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeDocument: TypedContractMethod<
    [documentHash: BytesLike],
    [void],
    "nonpayable"
  >;

  verifyDocument: TypedContractMethod<
    [documentHash: BytesLike],
    [
      [boolean, string, bigint] & {
        exists: boolean;
        issuer: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getMetadataHash"
  ): TypedContractMethod<[documentHash: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "registerDocument"
  ): TypedContractMethod<
    [documentHash: BytesLike, issuer: AddressLike, metadataHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeDocument"
  ): TypedContractMethod<[documentHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyDocument"
  ): TypedContractMethod<
    [documentHash: BytesLike],
    [
      [boolean, string, bigint] & {
        exists: boolean;
        issuer: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  filters: {};
}
