/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAuditTrail } from "./IAuditTrail";
export type { IIdentityRegistry } from "./IIdentityRegistry";
export type { IMedicalDocumentRegistry } from "./IMedicalDocumentRegistry";
export type { IPermissionManager } from "./IPermissionManager";
