/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type { AuditTrail, AuditTrailInterface } from "../../audit/AuditTrail";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "actor",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "patient",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "resourceId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "enum AuditTrail.ActionType",
        name: "action",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "timestamp",
        type: "uint64",
      },
    ],
    name: "AuditEvent",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "patient",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "resourceId",
        type: "bytes32",
      },
      {
        internalType: "enum AuditTrail.ActionType",
        name: "action",
        type: "uint8",
      },
    ],
    name: "logEvent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608080604052346100155760d7908161001b8239f35b600080fdfe6080806040526004361015601257600080fd5b600090813560e01c63de05fcc414602857600080fd5b34609d576060366003190112609d576004356001600160a01b038116908190036099576044356005811015609557825267ffffffffffffffff42166020830152602435917fab692841ac0f515c0b0f7b5a94d9ecf33960e9d565640721f81c13fb96de35d460403392a480f35b8380fd5b8280fd5b5080fdfea26469706673582212203b3e8c63ed6485ceab0ab309fd536e2278b05d3974e9e0e60b25b2eacbbb8a0664736f6c63430008140033";

type AuditTrailConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AuditTrailConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AuditTrail__factory extends ContractFactory {
  constructor(...args: AuditTrailConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      AuditTrail & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): AuditTrail__factory {
    return super.connect(runner) as AuditTrail__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AuditTrailInterface {
    return new Interface(_abi) as AuditTrailInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): AuditTrail {
    return new Contract(address, _abi, runner) as unknown as AuditTrail;
  }
}
