/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PermissionManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "grantPermission"
      | "guardianRegistry"
      | "hasAccess"
      | "identityRegistry"
      | "revokePermission"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PermissionGranted" | "PermissionRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "grantPermission",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "guardianRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasAccess",
    values: [AddressLike, AddressLike, BytesLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokePermission",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "grantPermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "guardianRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasAccess", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokePermission",
    data: BytesLike
  ): Result;
}

export namespace PermissionGrantedEvent {
  export type InputTuple = [
    patient: AddressLike,
    grantee: AddressLike,
    scope: BigNumberish
  ];
  export type OutputTuple = [patient: string, grantee: string, scope: bigint];
  export interface OutputObject {
    patient: string;
    grantee: string;
    scope: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PermissionRevokedEvent {
  export type InputTuple = [patient: AddressLike, grantee: AddressLike];
  export type OutputTuple = [patient: string, grantee: string];
  export interface OutputObject {
    patient: string;
    grantee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PermissionManager extends BaseContract {
  connect(runner?: ContractRunner | null): PermissionManager;
  waitForDeployment(): Promise<this>;

  interface: PermissionManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  grantPermission: TypedContractMethod<
    [
      patient: AddressLike,
      grantee: AddressLike,
      scope: BigNumberish,
      resourceId: BytesLike,
      expiresAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  guardianRegistry: TypedContractMethod<[], [string], "view">;

  hasAccess: TypedContractMethod<
    [
      patient: AddressLike,
      requester: AddressLike,
      documentId: BytesLike,
      documentType: BytesLike,
      institution: AddressLike
    ],
    [boolean],
    "view"
  >;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  revokePermission: TypedContractMethod<
    [patient: AddressLike, grantee: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "grantPermission"
  ): TypedContractMethod<
    [
      patient: AddressLike,
      grantee: AddressLike,
      scope: BigNumberish,
      resourceId: BytesLike,
      expiresAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "guardianRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "hasAccess"
  ): TypedContractMethod<
    [
      patient: AddressLike,
      requester: AddressLike,
      documentId: BytesLike,
      documentType: BytesLike,
      institution: AddressLike
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "revokePermission"
  ): TypedContractMethod<
    [patient: AddressLike, grantee: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "PermissionGranted"
  ): TypedContractEvent<
    PermissionGrantedEvent.InputTuple,
    PermissionGrantedEvent.OutputTuple,
    PermissionGrantedEvent.OutputObject
  >;
  getEvent(
    key: "PermissionRevoked"
  ): TypedContractEvent<
    PermissionRevokedEvent.InputTuple,
    PermissionRevokedEvent.OutputTuple,
    PermissionRevokedEvent.OutputObject
  >;

  filters: {
    "PermissionGranted(address,address,uint8)": TypedContractEvent<
      PermissionGrantedEvent.InputTuple,
      PermissionGrantedEvent.OutputTuple,
      PermissionGrantedEvent.OutputObject
    >;
    PermissionGranted: TypedContractEvent<
      PermissionGrantedEvent.InputTuple,
      PermissionGrantedEvent.OutputTuple,
      PermissionGrantedEvent.OutputObject
    >;

    "PermissionRevoked(address,address)": TypedContractEvent<
      PermissionRevokedEvent.InputTuple,
      PermissionRevokedEvent.OutputTuple,
      PermissionRevokedEvent.OutputObject
    >;
    PermissionRevoked: TypedContractEvent<
      PermissionRevokedEvent.InputTuple,
      PermissionRevokedEvent.OutputTuple,
      PermissionRevokedEvent.OutputObject
    >;
  };
}
