/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  Preflight,
  PreflightInterface,
} from "../../../src/preflight/Preflight";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_value",
        type: "uint256",
      },
    ],
    name: "set",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "value",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523460145760a0908161001a8239f35b600080fdfe6080806040526004361015601257600080fd5b600090813560e01c9081633fa4f24514604e57506360fe47b114603457600080fd5b34604b576020366003190112604b57600435815580f35b80fd5b90503460665781600319360112606657602091548152f35b5080fdfea264697066735822122008dafe702036860f1c161d2a36ed25962e9040f2e3a799d485f5300f7bc6e96e64736f6c63430008160033";

type PreflightConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PreflightConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Preflight__factory extends ContractFactory {
  constructor(...args: PreflightConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Preflight & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Preflight__factory {
    return super.connect(runner) as Preflight__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PreflightInterface {
    return new Interface(_abi) as PreflightInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Preflight {
    return new Contract(address, _abi, runner) as unknown as Preflight;
  }
}
