/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ClinicalEpisodeRegistry {
  export type ClinicalEpisodeStruct = {
    patient: AddressLike;
    openedBy: AddressLike;
    institution: AddressLike;
    episodeType: BytesLike;
    classification: BytesLike;
    openedAt: BigNumberish;
    active: boolean;
  };

  export type ClinicalEpisodeStructOutput = [
    patient: string,
    openedBy: string,
    institution: string,
    episodeType: string,
    classification: string,
    openedAt: bigint,
    active: boolean
  ] & {
    patient: string;
    openedBy: string;
    institution: string;
    episodeType: string;
    classification: string;
    openedAt: bigint;
    active: boolean;
  };
}

export interface ClinicalEpisodeRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "closeEpisode"
      | "doctorEpisodes"
      | "episodes"
      | "gateway"
      | "getEpisode"
      | "getEpisodesByDoctor"
      | "getEpisodesByPatient"
      | "identityRegistry"
      | "initialize"
      | "isTrustedForwarder"
      | "openEpisode"
      | "owner"
      | "patientEpisodes"
      | "proxiableUUID"
      | "renounceOwnership"
      | "setGateway"
      | "transferOwnership"
      | "trustedForwarder"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ClinicalEpisodeClosed"
      | "ClinicalEpisodeOpened"
      | "Initialized"
      | "OwnershipTransferred"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "closeEpisode",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "doctorEpisodes",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "episodes", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "gateway", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getEpisode",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEpisodesByDoctor",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEpisodesByPatient",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTrustedForwarder",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "openEpisode",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      BytesLike,
      BytesLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "patientEpisodes",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setGateway",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedForwarder",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeEpisode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "doctorEpisodes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "episodes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gateway", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getEpisode", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEpisodesByDoctor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEpisodesByPatient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isTrustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openEpisode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "patientEpisodes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setGateway", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace ClinicalEpisodeClosedEvent {
  export type InputTuple = [
    episodeId: BytesLike,
    patient: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    episodeId: string,
    patient: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    episodeId: string;
    patient: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClinicalEpisodeOpenedEvent {
  export type InputTuple = [
    episodeId: BytesLike,
    patient: AddressLike,
    doctor: AddressLike,
    institution: AddressLike,
    episodeType: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    episodeId: string,
    patient: string,
    doctor: string,
    institution: string,
    episodeType: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    episodeId: string;
    patient: string;
    doctor: string;
    institution: string;
    episodeType: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ClinicalEpisodeRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ClinicalEpisodeRegistry;
  waitForDeployment(): Promise<this>;

  interface: ClinicalEpisodeRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  closeEpisode: TypedContractMethod<
    [episodeId: BytesLike, doctor: AddressLike],
    [void],
    "nonpayable"
  >;

  doctorEpisodes: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  episodes: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, string, bigint, boolean] & {
        patient: string;
        openedBy: string;
        institution: string;
        episodeType: string;
        classification: string;
        openedAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  gateway: TypedContractMethod<[], [string], "view">;

  getEpisode: TypedContractMethod<
    [episodeId: BytesLike],
    [ClinicalEpisodeRegistry.ClinicalEpisodeStructOutput],
    "view"
  >;

  getEpisodesByDoctor: TypedContractMethod<
    [doctor: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [[string[], bigint] & { result: string[]; total: bigint }],
    "view"
  >;

  getEpisodesByPatient: TypedContractMethod<
    [patient: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [[string[], bigint] & { result: string[]; total: bigint }],
    "view"
  >;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<
    [identityAddress: AddressLike, forwarder: AddressLike],
    [void],
    "nonpayable"
  >;

  isTrustedForwarder: TypedContractMethod<
    [forwarder: AddressLike],
    [boolean],
    "view"
  >;

  openEpisode: TypedContractMethod<
    [
      episodeId: BytesLike,
      patient: AddressLike,
      institution: AddressLike,
      episodeType: BytesLike,
      classification: BytesLike,
      doctor: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  patientEpisodes: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setGateway: TypedContractMethod<
    [_gateway: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  trustedForwarder: TypedContractMethod<[], [string], "view">;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "closeEpisode"
  ): TypedContractMethod<
    [episodeId: BytesLike, doctor: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "doctorEpisodes"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "episodes"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, string, bigint, boolean] & {
        patient: string;
        openedBy: string;
        institution: string;
        episodeType: string;
        classification: string;
        openedAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "gateway"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEpisode"
  ): TypedContractMethod<
    [episodeId: BytesLike],
    [ClinicalEpisodeRegistry.ClinicalEpisodeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEpisodesByDoctor"
  ): TypedContractMethod<
    [doctor: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [[string[], bigint] & { result: string[]; total: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEpisodesByPatient"
  ): TypedContractMethod<
    [patient: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [[string[], bigint] & { result: string[]; total: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [identityAddress: AddressLike, forwarder: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isTrustedForwarder"
  ): TypedContractMethod<[forwarder: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "openEpisode"
  ): TypedContractMethod<
    [
      episodeId: BytesLike,
      patient: AddressLike,
      institution: AddressLike,
      episodeType: BytesLike,
      classification: BytesLike,
      doctor: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "patientEpisodes"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGateway"
  ): TypedContractMethod<[_gateway: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trustedForwarder"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "ClinicalEpisodeClosed"
  ): TypedContractEvent<
    ClinicalEpisodeClosedEvent.InputTuple,
    ClinicalEpisodeClosedEvent.OutputTuple,
    ClinicalEpisodeClosedEvent.OutputObject
  >;
  getEvent(
    key: "ClinicalEpisodeOpened"
  ): TypedContractEvent<
    ClinicalEpisodeOpenedEvent.InputTuple,
    ClinicalEpisodeOpenedEvent.OutputTuple,
    ClinicalEpisodeOpenedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "ClinicalEpisodeClosed(bytes32,address,uint64)": TypedContractEvent<
      ClinicalEpisodeClosedEvent.InputTuple,
      ClinicalEpisodeClosedEvent.OutputTuple,
      ClinicalEpisodeClosedEvent.OutputObject
    >;
    ClinicalEpisodeClosed: TypedContractEvent<
      ClinicalEpisodeClosedEvent.InputTuple,
      ClinicalEpisodeClosedEvent.OutputTuple,
      ClinicalEpisodeClosedEvent.OutputObject
    >;

    "ClinicalEpisodeOpened(bytes32,address,address,address,bytes32,uint64)": TypedContractEvent<
      ClinicalEpisodeOpenedEvent.InputTuple,
      ClinicalEpisodeOpenedEvent.OutputTuple,
      ClinicalEpisodeOpenedEvent.OutputObject
    >;
    ClinicalEpisodeOpened: TypedContractEvent<
      ClinicalEpisodeOpenedEvent.InputTuple,
      ClinicalEpisodeOpenedEvent.OutputTuple,
      ClinicalEpisodeOpenedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
