/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace MedicalOrderRegistry {
  export type MedicalOrderStruct = {
    patient: AddressLike;
    doctor: AddressLike;
    institution: AddressLike;
    episodeId: BytesLike;
    orderType: BytesLike;
    examType: BytesLike;
    assignedLab: AddressLike;
    status: BigNumberish;
    createdAt: BigNumberish;
  };

  export type MedicalOrderStructOutput = [
    patient: string,
    doctor: string,
    institution: string,
    episodeId: string,
    orderType: string,
    examType: string,
    assignedLab: string,
    status: bigint,
    createdAt: bigint
  ] & {
    patient: string;
    doctor: string;
    institution: string;
    episodeId: string;
    orderType: string;
    examType: string;
    assignedLab: string;
    status: bigint;
    createdAt: bigint;
  };
}

export interface MedicalOrderRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "assignLab"
      | "createOrder"
      | "doctorOrders"
      | "gateway"
      | "getOrder"
      | "getOrdersByDoctor"
      | "getOrdersByLab"
      | "getOrdersByPatient"
      | "identityRegistry"
      | "initialize"
      | "isTrustedForwarder"
      | "labOrders"
      | "orders"
      | "owner"
      | "patientOrders"
      | "proxiableUUID"
      | "renounceOwnership"
      | "setGateway"
      | "transferOwnership"
      | "trustedForwarder"
      | "updateStatus"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Initialized"
      | "LabAssigned"
      | "MedicalOrderCreated"
      | "OrderStatusUpdated"
      | "OwnershipTransferred"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assignLab",
    values: [BytesLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createOrder",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      BytesLike,
      BytesLike,
      BytesLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "doctorOrders",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "gateway", values?: undefined): string;
  encodeFunctionData(functionFragment: "getOrder", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getOrdersByDoctor",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrdersByLab",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrdersByPatient",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTrustedForwarder",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "labOrders",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "orders", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "patientOrders",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setGateway",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedForwarder",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateStatus",
    values: [BytesLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "assignLab", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "doctorOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gateway", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOrdersByDoctor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrdersByLab",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrdersByPatient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isTrustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "labOrders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "patientOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setGateway", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LabAssignedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    lab: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [orderId: string, lab: string, timestamp: bigint];
  export interface OutputObject {
    orderId: string;
    lab: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MedicalOrderCreatedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    patient: AddressLike,
    doctor: AddressLike,
    episodeId: BytesLike,
    examType: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    patient: string,
    doctor: string,
    episodeId: string,
    examType: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    orderId: string;
    patient: string;
    doctor: string;
    episodeId: string;
    examType: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderStatusUpdatedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    status: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    status: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    orderId: string;
    status: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MedicalOrderRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): MedicalOrderRegistry;
  waitForDeployment(): Promise<this>;

  interface: MedicalOrderRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  assignLab: TypedContractMethod<
    [orderId: BytesLike, lab: AddressLike, patient: AddressLike],
    [void],
    "nonpayable"
  >;

  createOrder: TypedContractMethod<
    [
      orderId: BytesLike,
      patient: AddressLike,
      institution: AddressLike,
      episodeId: BytesLike,
      orderType: BytesLike,
      examType: BytesLike,
      doctor: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  doctorOrders: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  gateway: TypedContractMethod<[], [string], "view">;

  getOrder: TypedContractMethod<
    [orderId: BytesLike],
    [MedicalOrderRegistry.MedicalOrderStructOutput],
    "view"
  >;

  getOrdersByDoctor: TypedContractMethod<
    [doctor: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [[string[], bigint] & { result: string[]; total: bigint }],
    "view"
  >;

  getOrdersByLab: TypedContractMethod<
    [lab: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [[string[], bigint] & { result: string[]; total: bigint }],
    "view"
  >;

  getOrdersByPatient: TypedContractMethod<
    [patient: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [[string[], bigint] & { result: string[]; total: bigint }],
    "view"
  >;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<
    [identityAddress: AddressLike, forwarder: AddressLike],
    [void],
    "nonpayable"
  >;

  isTrustedForwarder: TypedContractMethod<
    [forwarder: AddressLike],
    [boolean],
    "view"
  >;

  labOrders: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  orders: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint
      ] & {
        patient: string;
        doctor: string;
        institution: string;
        episodeId: string;
        orderType: string;
        examType: string;
        assignedLab: string;
        status: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  patientOrders: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setGateway: TypedContractMethod<
    [_gateway: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  trustedForwarder: TypedContractMethod<[], [string], "view">;

  updateStatus: TypedContractMethod<
    [orderId: BytesLike, status: BigNumberish, updater: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "assignLab"
  ): TypedContractMethod<
    [orderId: BytesLike, lab: AddressLike, patient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createOrder"
  ): TypedContractMethod<
    [
      orderId: BytesLike,
      patient: AddressLike,
      institution: AddressLike,
      episodeId: BytesLike,
      orderType: BytesLike,
      examType: BytesLike,
      doctor: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "doctorOrders"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "gateway"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getOrder"
  ): TypedContractMethod<
    [orderId: BytesLike],
    [MedicalOrderRegistry.MedicalOrderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOrdersByDoctor"
  ): TypedContractMethod<
    [doctor: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [[string[], bigint] & { result: string[]; total: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOrdersByLab"
  ): TypedContractMethod<
    [lab: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [[string[], bigint] & { result: string[]; total: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOrdersByPatient"
  ): TypedContractMethod<
    [patient: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [[string[], bigint] & { result: string[]; total: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [identityAddress: AddressLike, forwarder: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isTrustedForwarder"
  ): TypedContractMethod<[forwarder: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "labOrders"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "orders"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint
      ] & {
        patient: string;
        doctor: string;
        institution: string;
        episodeId: string;
        orderType: string;
        examType: string;
        assignedLab: string;
        status: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "patientOrders"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGateway"
  ): TypedContractMethod<[_gateway: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trustedForwarder"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateStatus"
  ): TypedContractMethod<
    [orderId: BytesLike, status: BigNumberish, updater: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "LabAssigned"
  ): TypedContractEvent<
    LabAssignedEvent.InputTuple,
    LabAssignedEvent.OutputTuple,
    LabAssignedEvent.OutputObject
  >;
  getEvent(
    key: "MedicalOrderCreated"
  ): TypedContractEvent<
    MedicalOrderCreatedEvent.InputTuple,
    MedicalOrderCreatedEvent.OutputTuple,
    MedicalOrderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderStatusUpdated"
  ): TypedContractEvent<
    OrderStatusUpdatedEvent.InputTuple,
    OrderStatusUpdatedEvent.OutputTuple,
    OrderStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "LabAssigned(bytes32,address,uint64)": TypedContractEvent<
      LabAssignedEvent.InputTuple,
      LabAssignedEvent.OutputTuple,
      LabAssignedEvent.OutputObject
    >;
    LabAssigned: TypedContractEvent<
      LabAssignedEvent.InputTuple,
      LabAssignedEvent.OutputTuple,
      LabAssignedEvent.OutputObject
    >;

    "MedicalOrderCreated(bytes32,address,address,bytes32,bytes32,uint64)": TypedContractEvent<
      MedicalOrderCreatedEvent.InputTuple,
      MedicalOrderCreatedEvent.OutputTuple,
      MedicalOrderCreatedEvent.OutputObject
    >;
    MedicalOrderCreated: TypedContractEvent<
      MedicalOrderCreatedEvent.InputTuple,
      MedicalOrderCreatedEvent.OutputTuple,
      MedicalOrderCreatedEvent.OutputObject
    >;

    "OrderStatusUpdated(bytes32,uint8,uint64)": TypedContractEvent<
      OrderStatusUpdatedEvent.InputTuple,
      OrderStatusUpdatedEvent.OutputTuple,
      OrderStatusUpdatedEvent.OutputObject
    >;
    OrderStatusUpdated: TypedContractEvent<
      OrderStatusUpdatedEvent.InputTuple,
      OrderStatusUpdatedEvent.OutputTuple,
      OrderStatusUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
