/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ClinicalEpisodeRegistry {
  export type ClinicalEpisodeStruct = {
    patient: AddressLike;
    openedBy: AddressLike;
    institution: AddressLike;
    episodeType: BytesLike;
    classification: BytesLike;
    openedAt: BigNumberish;
    active: boolean;
  };

  export type ClinicalEpisodeStructOutput = [
    patient: string,
    openedBy: string,
    institution: string,
    episodeType: string,
    classification: string,
    openedAt: bigint,
    active: boolean
  ] & {
    patient: string;
    openedBy: string;
    institution: string;
    episodeType: string;
    classification: string;
    openedAt: bigint;
    active: boolean;
  };
}

export interface ClinicalEpisodeRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "closeEpisode"
      | "episodes"
      | "getEpisode"
      | "identityRegistry"
      | "openEpisode"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ClinicalEpisodeClosed" | "ClinicalEpisodeOpened"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "closeEpisode",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "episodes", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getEpisode",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "openEpisode",
    values: [BytesLike, AddressLike, AddressLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "closeEpisode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "episodes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getEpisode", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openEpisode",
    data: BytesLike
  ): Result;
}

export namespace ClinicalEpisodeClosedEvent {
  export type InputTuple = [
    episodeId: BytesLike,
    patient: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    episodeId: string,
    patient: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    episodeId: string;
    patient: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClinicalEpisodeOpenedEvent {
  export type InputTuple = [
    episodeId: BytesLike,
    patient: AddressLike,
    doctor: AddressLike,
    institution: AddressLike,
    episodeType: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    episodeId: string,
    patient: string,
    doctor: string,
    institution: string,
    episodeType: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    episodeId: string;
    patient: string;
    doctor: string;
    institution: string;
    episodeType: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ClinicalEpisodeRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ClinicalEpisodeRegistry;
  waitForDeployment(): Promise<this>;

  interface: ClinicalEpisodeRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  closeEpisode: TypedContractMethod<
    [episodeId: BytesLike],
    [void],
    "nonpayable"
  >;

  episodes: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, string, bigint, boolean] & {
        patient: string;
        openedBy: string;
        institution: string;
        episodeType: string;
        classification: string;
        openedAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getEpisode: TypedContractMethod<
    [episodeId: BytesLike],
    [ClinicalEpisodeRegistry.ClinicalEpisodeStructOutput],
    "view"
  >;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  openEpisode: TypedContractMethod<
    [
      episodeId: BytesLike,
      patient: AddressLike,
      institution: AddressLike,
      episodeType: BytesLike,
      classification: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "closeEpisode"
  ): TypedContractMethod<[episodeId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "episodes"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, string, bigint, boolean] & {
        patient: string;
        openedBy: string;
        institution: string;
        episodeType: string;
        classification: string;
        openedAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEpisode"
  ): TypedContractMethod<
    [episodeId: BytesLike],
    [ClinicalEpisodeRegistry.ClinicalEpisodeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "openEpisode"
  ): TypedContractMethod<
    [
      episodeId: BytesLike,
      patient: AddressLike,
      institution: AddressLike,
      episodeType: BytesLike,
      classification: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ClinicalEpisodeClosed"
  ): TypedContractEvent<
    ClinicalEpisodeClosedEvent.InputTuple,
    ClinicalEpisodeClosedEvent.OutputTuple,
    ClinicalEpisodeClosedEvent.OutputObject
  >;
  getEvent(
    key: "ClinicalEpisodeOpened"
  ): TypedContractEvent<
    ClinicalEpisodeOpenedEvent.InputTuple,
    ClinicalEpisodeOpenedEvent.OutputTuple,
    ClinicalEpisodeOpenedEvent.OutputObject
  >;

  filters: {
    "ClinicalEpisodeClosed(bytes32,address,uint64)": TypedContractEvent<
      ClinicalEpisodeClosedEvent.InputTuple,
      ClinicalEpisodeClosedEvent.OutputTuple,
      ClinicalEpisodeClosedEvent.OutputObject
    >;
    ClinicalEpisodeClosed: TypedContractEvent<
      ClinicalEpisodeClosedEvent.InputTuple,
      ClinicalEpisodeClosedEvent.OutputTuple,
      ClinicalEpisodeClosedEvent.OutputObject
    >;

    "ClinicalEpisodeOpened(bytes32,address,address,address,bytes32,uint64)": TypedContractEvent<
      ClinicalEpisodeOpenedEvent.InputTuple,
      ClinicalEpisodeOpenedEvent.OutputTuple,
      ClinicalEpisodeOpenedEvent.OutputObject
    >;
    ClinicalEpisodeOpened: TypedContractEvent<
      ClinicalEpisodeOpenedEvent.InputTuple,
      ClinicalEpisodeOpenedEvent.OutputTuple,
      ClinicalEpisodeOpenedEvent.OutputObject
    >;
  };
}
