/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ClinicalEpisodeRegistry } from "./ClinicalEpisodeRegistry";
export type { MedicalDocumentRegistry } from "./MedicalDocumentRegistry";
export type { MedicalOrderRegistry } from "./MedicalOrderRegistry";
