/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MedicalDocumentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "documents" | "identityRegistry" | "registerDocument"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DocumentRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "documents",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerDocument",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      BytesLike,
      BytesLike,
      BytesLike,
      string,
      BytesLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(functionFragment: "documents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerDocument",
    data: BytesLike
  ): Result;
}

export namespace DocumentRegisteredEvent {
  export type InputTuple = [
    documentId: BytesLike,
    patient: AddressLike,
    issuer: AddressLike
  ];
  export type OutputTuple = [
    documentId: string,
    patient: string,
    issuer: string
  ];
  export interface OutputObject {
    documentId: string;
    patient: string;
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MedicalDocumentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): MedicalDocumentRegistry;
  waitForDeployment(): Promise<this>;

  interface: MedicalDocumentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  documents: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint
      ] & {
        patient: string;
        issuer: string;
        institution: string;
        documentType: string;
        clinicalHash: string;
        episodeId: string;
        cid: string;
        standard: string;
        classification: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  registerDocument: TypedContractMethod<
    [
      documentId: BytesLike,
      patient: AddressLike,
      institution: AddressLike,
      documentType: BytesLike,
      clinicalHash: BytesLike,
      episodeId: BytesLike,
      cid: string,
      standard: BytesLike,
      classification: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "documents"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint
      ] & {
        patient: string;
        issuer: string;
        institution: string;
        documentType: string;
        clinicalHash: string;
        episodeId: string;
        cid: string;
        standard: string;
        classification: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerDocument"
  ): TypedContractMethod<
    [
      documentId: BytesLike,
      patient: AddressLike,
      institution: AddressLike,
      documentType: BytesLike,
      clinicalHash: BytesLike,
      episodeId: BytesLike,
      cid: string,
      standard: BytesLike,
      classification: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DocumentRegistered"
  ): TypedContractEvent<
    DocumentRegisteredEvent.InputTuple,
    DocumentRegisteredEvent.OutputTuple,
    DocumentRegisteredEvent.OutputObject
  >;

  filters: {
    "DocumentRegistered(bytes32,address,address)": TypedContractEvent<
      DocumentRegisteredEvent.InputTuple,
      DocumentRegisteredEvent.OutputTuple,
      DocumentRegisteredEvent.OutputObject
    >;
    DocumentRegistered: TypedContractEvent<
      DocumentRegisteredEvent.InputTuple,
      DocumentRegisteredEvent.OutputTuple,
      DocumentRegisteredEvent.OutputObject
    >;
  };
}
