/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface HealthProofGatewayInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "assignLabViaGateway"
      | "closeEpisodeViaGateway"
      | "createEpisode"
      | "createMedicalOrder"
      | "grantAccess"
      | "guardianRegistry"
      | "identityRegistry"
      | "isTrustedForwarder"
      | "kernel"
      | "registerMedicalDocument"
      | "revokeAccess"
      | "trustedForwarder"
      | "updateOrderStatusViaGateway"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccessGranted"
      | "AccessRevoked"
      | "EpisodeClosedViaGateway"
      | "EpisodeCreated"
      | "LabAssignedViaGateway"
      | "MedicalDocumentRegistered"
      | "MedicalOrderCreated"
      | "OrderStatusUpdatedViaGateway"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "assignLabViaGateway",
    values: [BytesLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "closeEpisodeViaGateway",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createEpisode",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      BytesLike,
      BytesLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createMedicalOrder",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      BytesLike,
      BytesLike,
      BytesLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "grantAccess",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "guardianRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isTrustedForwarder",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "kernel", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerMedicalDocument",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      BytesLike,
      BytesLike,
      BytesLike,
      string,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAccess",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedForwarder",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateOrderStatusViaGateway",
    values: [BytesLike, BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "assignLabViaGateway",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeEpisodeViaGateway",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEpisode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMedicalOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "guardianRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTrustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "kernel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerMedicalDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateOrderStatusViaGateway",
    data: BytesLike
  ): Result;
}

export namespace AccessGrantedEvent {
  export type InputTuple = [
    patient: AddressLike,
    grantee: AddressLike,
    resourceId: BytesLike
  ];
  export type OutputTuple = [
    patient: string,
    grantee: string,
    resourceId: string
  ];
  export interface OutputObject {
    patient: string;
    grantee: string;
    resourceId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccessRevokedEvent {
  export type InputTuple = [patient: AddressLike, grantee: AddressLike];
  export type OutputTuple = [patient: string, grantee: string];
  export interface OutputObject {
    patient: string;
    grantee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EpisodeClosedViaGatewayEvent {
  export type InputTuple = [episodeId: BytesLike, doctor: AddressLike];
  export type OutputTuple = [episodeId: string, doctor: string];
  export interface OutputObject {
    episodeId: string;
    doctor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EpisodeCreatedEvent {
  export type InputTuple = [
    episodeId: BytesLike,
    patient: AddressLike,
    doctor: AddressLike
  ];
  export type OutputTuple = [
    episodeId: string,
    patient: string,
    doctor: string
  ];
  export interface OutputObject {
    episodeId: string;
    patient: string;
    doctor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LabAssignedViaGatewayEvent {
  export type InputTuple = [
    orderId: BytesLike,
    lab: AddressLike,
    patient: AddressLike
  ];
  export type OutputTuple = [orderId: string, lab: string, patient: string];
  export interface OutputObject {
    orderId: string;
    lab: string;
    patient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MedicalDocumentRegisteredEvent {
  export type InputTuple = [
    documentId: BytesLike,
    patient: AddressLike,
    episodeId: BytesLike
  ];
  export type OutputTuple = [
    documentId: string,
    patient: string,
    episodeId: string
  ];
  export interface OutputObject {
    documentId: string;
    patient: string;
    episodeId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MedicalOrderCreatedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    patient: AddressLike,
    episodeId: BytesLike,
    doctor: AddressLike
  ];
  export type OutputTuple = [
    orderId: string,
    patient: string,
    episodeId: string,
    doctor: string
  ];
  export interface OutputObject {
    orderId: string;
    patient: string;
    episodeId: string;
    doctor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderStatusUpdatedViaGatewayEvent {
  export type InputTuple = [
    orderId: BytesLike,
    status: BigNumberish,
    updater: AddressLike
  ];
  export type OutputTuple = [orderId: string, status: bigint, updater: string];
  export interface OutputObject {
    orderId: string;
    status: bigint;
    updater: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HealthProofGateway extends BaseContract {
  connect(runner?: ContractRunner | null): HealthProofGateway;
  waitForDeployment(): Promise<this>;

  interface: HealthProofGatewayInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assignLabViaGateway: TypedContractMethod<
    [orderId: BytesLike, lab: AddressLike, patient: AddressLike],
    [void],
    "nonpayable"
  >;

  closeEpisodeViaGateway: TypedContractMethod<
    [episodeId: BytesLike, doctor: AddressLike],
    [void],
    "nonpayable"
  >;

  createEpisode: TypedContractMethod<
    [
      episodeId: BytesLike,
      patient: AddressLike,
      institution: AddressLike,
      episodeType: BytesLike,
      classification: BytesLike,
      doctor: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  createMedicalOrder: TypedContractMethod<
    [
      orderId: BytesLike,
      patient: AddressLike,
      institution: AddressLike,
      episodeId: BytesLike,
      orderType: BytesLike,
      examType: BytesLike,
      doctor: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  grantAccess: TypedContractMethod<
    [
      patient: AddressLike,
      grantee: AddressLike,
      scope: BigNumberish,
      resourceId: BytesLike,
      expiresAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  guardianRegistry: TypedContractMethod<[], [string], "view">;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  isTrustedForwarder: TypedContractMethod<
    [forwarder: AddressLike],
    [boolean],
    "view"
  >;

  kernel: TypedContractMethod<[], [string], "view">;

  registerMedicalDocument: TypedContractMethod<
    [
      documentId: BytesLike,
      patient: AddressLike,
      institution: AddressLike,
      documentType: BytesLike,
      clinicalHash: BytesLike,
      episodeId: BytesLike,
      cid: string,
      standard: BytesLike,
      classification: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  revokeAccess: TypedContractMethod<
    [patient: AddressLike, grantee: AddressLike],
    [void],
    "nonpayable"
  >;

  trustedForwarder: TypedContractMethod<[], [string], "view">;

  updateOrderStatusViaGateway: TypedContractMethod<
    [orderId: BytesLike, status: BigNumberish, updater: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assignLabViaGateway"
  ): TypedContractMethod<
    [orderId: BytesLike, lab: AddressLike, patient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "closeEpisodeViaGateway"
  ): TypedContractMethod<
    [episodeId: BytesLike, doctor: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createEpisode"
  ): TypedContractMethod<
    [
      episodeId: BytesLike,
      patient: AddressLike,
      institution: AddressLike,
      episodeType: BytesLike,
      classification: BytesLike,
      doctor: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createMedicalOrder"
  ): TypedContractMethod<
    [
      orderId: BytesLike,
      patient: AddressLike,
      institution: AddressLike,
      episodeId: BytesLike,
      orderType: BytesLike,
      examType: BytesLike,
      doctor: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grantAccess"
  ): TypedContractMethod<
    [
      patient: AddressLike,
      grantee: AddressLike,
      scope: BigNumberish,
      resourceId: BytesLike,
      expiresAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "guardianRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isTrustedForwarder"
  ): TypedContractMethod<[forwarder: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "kernel"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerMedicalDocument"
  ): TypedContractMethod<
    [
      documentId: BytesLike,
      patient: AddressLike,
      institution: AddressLike,
      documentType: BytesLike,
      clinicalHash: BytesLike,
      episodeId: BytesLike,
      cid: string,
      standard: BytesLike,
      classification: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeAccess"
  ): TypedContractMethod<
    [patient: AddressLike, grantee: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "trustedForwarder"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateOrderStatusViaGateway"
  ): TypedContractMethod<
    [orderId: BytesLike, status: BigNumberish, updater: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AccessGranted"
  ): TypedContractEvent<
    AccessGrantedEvent.InputTuple,
    AccessGrantedEvent.OutputTuple,
    AccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "AccessRevoked"
  ): TypedContractEvent<
    AccessRevokedEvent.InputTuple,
    AccessRevokedEvent.OutputTuple,
    AccessRevokedEvent.OutputObject
  >;
  getEvent(
    key: "EpisodeClosedViaGateway"
  ): TypedContractEvent<
    EpisodeClosedViaGatewayEvent.InputTuple,
    EpisodeClosedViaGatewayEvent.OutputTuple,
    EpisodeClosedViaGatewayEvent.OutputObject
  >;
  getEvent(
    key: "EpisodeCreated"
  ): TypedContractEvent<
    EpisodeCreatedEvent.InputTuple,
    EpisodeCreatedEvent.OutputTuple,
    EpisodeCreatedEvent.OutputObject
  >;
  getEvent(
    key: "LabAssignedViaGateway"
  ): TypedContractEvent<
    LabAssignedViaGatewayEvent.InputTuple,
    LabAssignedViaGatewayEvent.OutputTuple,
    LabAssignedViaGatewayEvent.OutputObject
  >;
  getEvent(
    key: "MedicalDocumentRegistered"
  ): TypedContractEvent<
    MedicalDocumentRegisteredEvent.InputTuple,
    MedicalDocumentRegisteredEvent.OutputTuple,
    MedicalDocumentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "MedicalOrderCreated"
  ): TypedContractEvent<
    MedicalOrderCreatedEvent.InputTuple,
    MedicalOrderCreatedEvent.OutputTuple,
    MedicalOrderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderStatusUpdatedViaGateway"
  ): TypedContractEvent<
    OrderStatusUpdatedViaGatewayEvent.InputTuple,
    OrderStatusUpdatedViaGatewayEvent.OutputTuple,
    OrderStatusUpdatedViaGatewayEvent.OutputObject
  >;

  filters: {
    "AccessGranted(address,address,bytes32)": TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;
    AccessGranted: TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;

    "AccessRevoked(address,address)": TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;
    AccessRevoked: TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;

    "EpisodeClosedViaGateway(bytes32,address)": TypedContractEvent<
      EpisodeClosedViaGatewayEvent.InputTuple,
      EpisodeClosedViaGatewayEvent.OutputTuple,
      EpisodeClosedViaGatewayEvent.OutputObject
    >;
    EpisodeClosedViaGateway: TypedContractEvent<
      EpisodeClosedViaGatewayEvent.InputTuple,
      EpisodeClosedViaGatewayEvent.OutputTuple,
      EpisodeClosedViaGatewayEvent.OutputObject
    >;

    "EpisodeCreated(bytes32,address,address)": TypedContractEvent<
      EpisodeCreatedEvent.InputTuple,
      EpisodeCreatedEvent.OutputTuple,
      EpisodeCreatedEvent.OutputObject
    >;
    EpisodeCreated: TypedContractEvent<
      EpisodeCreatedEvent.InputTuple,
      EpisodeCreatedEvent.OutputTuple,
      EpisodeCreatedEvent.OutputObject
    >;

    "LabAssignedViaGateway(bytes32,address,address)": TypedContractEvent<
      LabAssignedViaGatewayEvent.InputTuple,
      LabAssignedViaGatewayEvent.OutputTuple,
      LabAssignedViaGatewayEvent.OutputObject
    >;
    LabAssignedViaGateway: TypedContractEvent<
      LabAssignedViaGatewayEvent.InputTuple,
      LabAssignedViaGatewayEvent.OutputTuple,
      LabAssignedViaGatewayEvent.OutputObject
    >;

    "MedicalDocumentRegistered(bytes32,address,bytes32)": TypedContractEvent<
      MedicalDocumentRegisteredEvent.InputTuple,
      MedicalDocumentRegisteredEvent.OutputTuple,
      MedicalDocumentRegisteredEvent.OutputObject
    >;
    MedicalDocumentRegistered: TypedContractEvent<
      MedicalDocumentRegisteredEvent.InputTuple,
      MedicalDocumentRegisteredEvent.OutputTuple,
      MedicalDocumentRegisteredEvent.OutputObject
    >;

    "MedicalOrderCreated(bytes32,address,bytes32,address)": TypedContractEvent<
      MedicalOrderCreatedEvent.InputTuple,
      MedicalOrderCreatedEvent.OutputTuple,
      MedicalOrderCreatedEvent.OutputObject
    >;
    MedicalOrderCreated: TypedContractEvent<
      MedicalOrderCreatedEvent.InputTuple,
      MedicalOrderCreatedEvent.OutputTuple,
      MedicalOrderCreatedEvent.OutputObject
    >;

    "OrderStatusUpdatedViaGateway(bytes32,uint8,address)": TypedContractEvent<
      OrderStatusUpdatedViaGatewayEvent.InputTuple,
      OrderStatusUpdatedViaGatewayEvent.OutputTuple,
      OrderStatusUpdatedViaGatewayEvent.OutputObject
    >;
    OrderStatusUpdatedViaGateway: TypedContractEvent<
      OrderStatusUpdatedViaGatewayEvent.InputTuple,
      OrderStatusUpdatedViaGatewayEvent.OutputTuple,
      OrderStatusUpdatedViaGatewayEvent.OutputObject
    >;
  };
}
