/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HealthProofGateway } from "./HealthProofGateway";
export type { HealthProofKernel } from "./HealthProofKernel";
export type { HealthProofProtocol } from "./HealthProofProtocol";
