/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAuditTrail,
  IAuditTrailInterface,
} from "../../interfaces/IAuditTrail";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "eventType",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "actor",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "subject",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "log",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAuditTrail__factory {
  static readonly abi = _abi;
  static createInterface(): IAuditTrailInterface {
    return new Interface(_abi) as IAuditTrailInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IAuditTrail {
    return new Contract(address, _abi, runner) as unknown as IAuditTrail;
  }
}
