/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAuditTrail__factory } from "./IAuditTrail__factory";
export { IIdentityRegistry__factory } from "./IIdentityRegistry__factory";
export { IMedicalDocumentRegistry__factory } from "./IMedicalDocumentRegistry__factory";
export { IPermissionManager__factory } from "./IPermissionManager__factory";
