import type { LoincEntry } from "../loinc/types";

export type { LoincEntry };

export const CHILE_LOINC_SUBSET: LoincEntry[] = [
  {
    code: "26464-8",
    display: "Leukocytes [#/volume] in Blood",
    spanishDisplay: "Leucocitos (WBC) en sangre",
    aliases: ["leucocitos", "white blood cells", "WBC"],
    component: "Leukocytes",
    system: "Blood",
    scale: "Qn",
  },
  {
    code: "26485-3",
    display: "Erythrocytes [#/volume] in Blood",
    spanishDisplay: "Eritrocitos (RBC) en sangre",
    aliases: ["eritrocitos", "red blood cells", "RBC"],
    component: "Erythrocytes",
    system: "Blood",
    scale: "Qn",
  },
  {
    code: "26515-7",
    display: "Hemoglobin [Mass/volume] in Blood",
    spanishDisplay: "Hemoglobina (Hgb) en sangre",
    aliases: ["hemoglobina", "Hgb"],
    component: "Hemoglobin",
    system: "Blood",
    scale: "Qn",
  },
  {
    code: "26453-1",
    display: "Hematocrit [Volume Fraction] of Blood",
    spanishDisplay: "Hematocrito (Hct) en sangre",
    aliases: ["hematocrito", "Hct"],
    component: "Hematocrit",
    system: "Blood",
    scale: "Qn",
  },
  {
    code: "26511-9",
    display: "Neutrophils/100 leukocytes in Blood",
    spanishDisplay: "Neutrófilos en sangre",
    aliases: ["neutrofilos"],
    component: "Neutrophils/100 leukocytes",
    system: "Blood",
    scale: "Qn",
  },
  {
    code: "26450-7",
    display: "Platelets [#/volume] in Blood",
    spanishDisplay: "Plaquetas en sangre",
    aliases: ["plaquetas", "platelets"],
    component: "Platelets",
    system: "Blood",
    scale: "Qn",
  },
  {
    code: "26508-5",
    display: "Lymphocytes/100 leukocytes in Blood",
    spanishDisplay: "Linfocitos en sangre",
    aliases: ["linfocitos"],
    component: "Lymphocytes/100 leukocytes",
    system: "Blood",
    scale: "Qn",
  },
  {
    code: "26507-7",
    display: "Monocytes/100 leukocytes in Blood",
    spanishDisplay: "Monocitos en sangre",
    aliases: ["monocitos"],
    component: "Monocytes/100 leukocytes",
    system: "Blood",
    scale: "Qn",
  },
  {
    code: "26514-0",
    display: "Basophils/100 leukocytes in Blood",
    spanishDisplay: "Basófilos en sangre",
    aliases: ["basofilos"],
    component: "Basophils/100 leukocytes",
    system: "Blood",
    scale: "Qn",
  },
  {
    code: "26513-2",
    display: "Eosinophils/100 leukocytes in Blood",
    spanishDisplay: "Eosinófilos en sangre",
    aliases: ["eosinofilos"],
    component: "Eosinophils/100 leukocytes",
    system: "Blood",
    scale: "Qn",
  },
  {
    code: "26510-1",
    display: "MCV [Entitic volume]",
    spanishDisplay: "Volumen corpuscular medio (MCV)",
    aliases: ["MCV"],
    component: "MCV",
    system: "Blood",
    scale: "Qn",
  },
  {
    code: "26512-7",
    display: "MCH [Entitic mass]",
    spanishDisplay: "Hemoglobina corpuscular media (MCH)",
    aliases: ["MCH"],
    component: "MCH",
    system: "RBC",
    scale: "Qn",
  },
  {
    code: "26509-3",
    display: "MCHC [Mass/volume]",
    spanishDisplay: "Concentración de hemoglobina corpuscular media (MCHC)",
    aliases: ["MCHC"],
    component: "MCHC",
    system: "Blood",
    scale: "Qn",
  },
  {
    code: "24323-8",
    display: "Glucose [Mass/volume] in Serum or Plasma",
    spanishDisplay: "Glucosa en suero o plasma",
    aliases: ["glucosa", "glucose"],
    component: "Glucose",
    system: "Ser/Plas",
    scale: "Qn",
  },
  {
    code: "2339-0",
    display: "Glucose [Mass/volume] in Blood",
    spanishDisplay: "Glucosa en sangre",
    aliases: ["glucosa sangre"],
    component: "Glucose",
    system: "Blood",
    scale: "Qn",
  },
  {
    code: "2951-2",
    display: "Sodium [Moles/volume] in Serum or Plasma",
    spanishDisplay: "Sodio en suero o plasma",
    aliases: ["sodio", "sodium", "Na"],
    component: "Sodium",
    system: "Ser/Plas",
    scale: "Qn",
  },
  {
    code: "2823-3",
    display: "Potassium [Moles/volume] in Serum or Plasma",
    spanishDisplay: "Potasio en suero o plasma",
    aliases: ["potasio", "potassium", "K"],
    component: "Potassium",
    system: "Ser/Plas",
    scale: "Qn",
  },
  {
    code: "17861-6",
    display: "Cholesterol [Mass/volume] in Serum or Plasma",
    spanishDisplay: "Colesterol total en suero o plasma",
    aliases: ["colesterol total", "total cholesterol"],
    component: "Cholesterol",
    system: "Ser/Plas",
    scale: "Qn",
  },
  {
    code: "2093-3",
    display: "Cholesterol in HDL [Mass/volume] in Serum or Plasma",
    spanishDisplay: "Colesterol HDL en suero o plasma",
    aliases: ["colesterol HDL", "HDL"],
    component: "Cholesterol in HDL",
    system: "Ser/Plas",
    scale: "Qn",
  },
  {
    code: "2085-9",
    display: "Cholesterol in LDL [Mass/volume] in Serum or Plasma",
    spanishDisplay: "Colesterol LDL en suero o plasma",
    aliases: ["colesterol LDL", "LDL"],
    component: "Cholesterol in LDL",
    system: "Ser/Plas",
    scale: "Qn",
  },
  {
    code: "2571-8",
    display: "Triglyceride [Mass/volume] in Serum or Plasma",
    spanishDisplay: "Triglicéridos en suero o plasma",
    aliases: ["trigliceridos", "triglycerides"],
    component: "Triglyceride",
    system: "Ser/Plas",
    scale: "Qn",
  },
  {
    code: "13457-9",
    display: "Cholesterol in VLDL [Mass/volume] in Serum or Plasma",
    spanishDisplay: "Colesterol VLDL en suero o plasma",
    aliases: ["VLDL", "colesterol VLDL"],
    component: "Cholesterol in VLDL",
    system: "Ser/Plas",
    scale: "Qn",
  },
  {
    code: "2160-0",
    display: "Creatinine [Mass/volume] in Serum or Plasma",
    spanishDisplay: "Creatinina en suero o plasma",
    aliases: ["creatinina", "creatinine"],
    component: "Creatinine",
    system: "Ser/Plas",
    scale: "Qn",
  },
  {
    code: "38483-4",
    display: "Creatinine [Mass/volume] in 24 hour Urine",
    spanishDisplay: "Creatinina en orina de 24 horas",
    aliases: ["creatinina orina"],
    component: "Creatinine",
    system: "Urine",
    scale: "Qn",
  },
  {
    code: "33717-0",
    display: "Thyrotropin [Units/volume] in Serum or Plasma",
    spanishDisplay: "TSH en suero o plasma",
    aliases: ["TSH", "tirotropina"],
    component: "Thyrotropin",
    system: "Ser/Plas",
    scale: "Qn",
  },
  {
    code: "24325-3",
    display: "Hemoglobin A1c/Hemoglobin.total in Blood",
    spanishDisplay: "Hemoglobina glicosilada (HbA1c) en sangre",
    aliases: ["HbA1c", "hemoglobina glicosilada", "A1c"],
    component: "Hemoglobin A1c/Hemoglobin.total",
    system: "Blood",
    scale: "Qn",
  },
  {
    code: "82258-8",
    display: "25-hydroxyvitamin D [Mass/volume] in Serum or Plasma",
    spanishDisplay: "Vitamina D 25-hidroxi en suero o plasma",
    aliases: ["vitamina D", "25-OH vitamina D"],
    component: "25-hydroxyvitamin D",
    system: "Ser/Plas",
    scale: "Qn",
  },
  {
    code: "1742-6",
    display: "Bilirubin.total [Mass/volume] in Serum or Plasma",
    spanishDisplay: "Bilirrubina total en suero o plasma",
    aliases: ["bilirrubina total"],
    component: "Bilirubin.total",
    system: "Ser/Plas",
    scale: "Qn",
  },
  {
    code: "1751-7",
    display: "Albumin [Mass/volume] in Serum or Plasma",
    spanishDisplay: "Albúmina en suero o plasma",
    aliases: ["albumina"],
    component: "Albumin",
    system: "Ser/Plas",
    scale: "Qn",
  },
  {
    code: "10834-0",
    display: "Protein fraction [Interpretation] in Serum or Plasma",
    spanishDisplay: "Proteínas totales en suero o plasma",
    aliases: ["proteinas totales"],
    component: "Protein fraction",
    system: "Ser/Plas",
    scale: "Qn",
  },
  {
    code: "1975-2",
    display: "Bilirubin.total [Mass/volume] in Blood or Plasma",
    spanishDisplay: "Bilirrubina total en sangre/plasma",
    aliases: ["bilirrubina"],
    component: "Bilirubin.total",
    system: "Blood/Plasma",
    scale: "Qn",
  },
  {
    code: "6767-7",
    display:
      "Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma",
    spanishDisplay: "Fosfatasa alcalina en suero o plasma",
    aliases: ["fosfatasa alcalina", "FA"],
    component: "Alkaline phosphatase",
    system: "Ser/Plas",
    scale: "Qn",
  },
  {
    code: "1916-6",
    display:
      "Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma",
    spanishDisplay: "Alanina aminotransferasa (ALT) en suero o plasma",
    aliases: ["ALT", "TGP", "alanina aminotransferasa"],
    component: "Alanine aminotransferase",
    system: "Ser/Plas",
    scale: "Qn",
  },
  {
    code: "1920-8",
    display:
      "Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma",
    spanishDisplay: "Aspartato aminotransferasa (AST) en suero o plasma",
    aliases: ["AST", "TGO", "aspartato aminotransferasa"],
    component: "Aspartate aminotransferase",
    system: "Ser/Plas",
    scale: "Qn",
  },
  {
    code: "2710-6",
    display: "Urea nitrogen [Mass/volume] in Serum or Plasma",
    spanishDisplay: "Nitrógeno de urea en suero o plasma",
    aliases: ["urea", "BUN"],
    component: "Urea nitrogen",
    system: "Ser/Plas",
    scale: "Qn",
  },
  {
    code: "3084-1",
    display: "Uric acid [Mass/volume] in Serum or Plasma",
    spanishDisplay: "Ácido úrico en suero o plasma",
    aliases: ["acido urico", "uric acid"],
    component: "Uric acid",
    system: "Ser/Plas",
    scale: "Qn",
  },
  {
    code: "14682-9",
    display: "Creatinine [Mass/volume] in Serum or Plasma by Jaffe method",
    spanishDisplay: "Creatinina en suero o plasma por método Jaffe",
    aliases: ["creatinina jaffe"],
    component: "Creatinine",
    system: "Ser/Plas",
    scale: "Qn",
  },
  {
    code: "14959-1",
    display: "Microalbumin/Creatinine [Mass Ratio] in 24 hour Urine",
    spanishDisplay: "Microalbúmina/Creatinina en orina de 24 horas",
    aliases: ["albuminuria creatinina"],
    component: "Microalbumin/Creatinine",
    system: "Urine",
    scale: "Qn",
  },
  {
    code: "3094-0",
    display: "Urea [Mass/volume] in Serum or Plasma",
    spanishDisplay: "Urea en suero o plasma",
    aliases: ["urea"],
    component: "Urea",
    system: "Ser/Plas",
    scale: "Qn",
  },
  {
    code: "20959-7",
    display: "Protein [Mass/volume] in Urine",
    spanishDisplay: "Proteínas en orina",
    aliases: ["proteinuria"],
    component: "Protein",
    system: "Urine",
    scale: "Qn",
  },
  {
    code: "5792-7",
    display: "Glucose [Mass/volume] in Urine",
    spanishDisplay: "Glucosa en orina",
    aliases: ["glucosa orina"],
    component: "Glucose",
    system: "Urine",
    scale: "Qn",
  },
  {
    code: "5802-4",
    display: "Nitrite [Presence] in Urine",
    spanishDisplay: "Nitritos en orina",
    aliases: ["nitritos"],
    component: "Nitrite",
    system: "Urine",
    scale: "Ord",
  },
  {
    code: "5799-8",
    display: "Leukocyte esterase [Presence] in Urine",
    spanishDisplay: "Esterasas leucocitarias en orina",
    aliases: ["esterasas leucocitarias"],
    component: "Leukocyte esterase",
    system: "Urine",
    scale: "Ord",
  },
  {
    code: "5770-3",
    display: "Leukocytes [Presence] in Urine",
    spanishDisplay: "Leucocitos en orina",
    aliases: ["leucocitos orina", "leucocitos en orina"],
    component: "Leukocytes",
    system: "Urine",
    scale: "Ord",
  },
  {
    code: "58446-0",
    display: "Bacteria [#/area] in Urine sediment by Microscopy",
    spanishDisplay: "Bacterias en sedimento urinario",
    aliases: ["bacterias"],
    component: "Bacteria",
    system: "Urine",
    scale: "Qn",
  },
  {
    code: "5767-9",
    display: "Turbidity [Appearance] of Urine",
    spanishDisplay: "Turbidez de la orina",
    aliases: ["turbidez"],
    component: "Turbidity",
    system: "Urine",
    scale: "Ord",
  },
  {
    code: "5778-6",
    display: "Color of Urine",
    spanishDisplay: "Color de la orina",
    aliases: ["color"],
    component: "Color",
    system: "Urine",
    scale: "Ord",
  },
  {
    code: "5803-2",
    display: "pH [Units] in Urine",
    spanishDisplay: "pH en orina",
    aliases: ["pH"],
    component: "pH",
    system: "Urine",
    scale: "Qn",
  },
  {
    code: "5811-5",
    display: "Specific gravity of Urine",
    spanishDisplay: "Densidad específica en orina",
    aliases: ["densidad"],
    component: "Specific gravity",
    system: "Urine",
    scale: "Qn",
  },
  {
    code: "5794-3",
    display: "Hemoglobin [Presence] in Urine",
    spanishDisplay: "Hemoglobina en orina",
    aliases: ["sangre oculta", "hemoglobina"],
    component: "Hemoglobin",
    system: "Urine",
    scale: "Ord",
  },
  {
    code: "5800-4",
    display: "Ketones [Presence] in Urine",
    spanishDisplay: "Cetonas en orina",
    aliases: ["cetonas"],
    component: "Ketones",
    system: "Urine",
    scale: "Ord",
  },
  {
    code: "5790-1",
    display: "Protein [Presence] in Urine",
    spanishDisplay: "Proteínas en orina",
    aliases: ["proteinas"],
    component: "Protein",
    system: "Urine",
    scale: "Ord",
  },
  {
    code: "5787-7",
    display: "Epithelial cells [Presence] in Urine",
    spanishDisplay: "Células epiteliales en orina",
    aliases: ["celulas epiteliales"],
    component: "Epithelial cells",
    system: "Urine",
    scale: "Ord",
  },
];

export const OBSTETRIC_LOINC_SUBSET: LoincEntry[] = [
  {
    code: "26828-7",
    display: "Biparietal diameter [Length] by US",
    spanishDisplay: "Diámetro biparietal (BPD) por ecografía",
    aliases: ["BPD", "biparietal", "diametro biparietal"],
    component: "Biparietal diameter",
    system: "US",
    scale: "Qn",
  },
  {
    code: "11820-8",
    display: "Head circumference [Length] by US",
    spanishDisplay: "Circunferencia de cabeza (HC) por ecografía",
    aliases: ["HC", "head circumference", "circunferencia de cabeza"],
    component: "Head circumference",
    system: "US",
    scale: "Qn",
  },
  {
    code: "11824-0",
    display: "Abdominal circumference [Length] by US",
    spanishDisplay: "Circunferencia abdominal (AC) por ecografía",
    aliases: ["AC", "abdominal circumference", "circunferencia abdominal"],
    component: "Abdominal circumference",
    system: "US",
    scale: "Qn",
  },
  {
    code: "11920-8",
    display: "Femur length [Length] by US",
    spanishDisplay: "Longitud de fémur (FL) por ecografía",
    aliases: ["FL", "femur length", "longitud de femur"],
    component: "Femur length",
    system: "US",
    scale: "Qn",
  },
  {
    code: "72132-8",
    display: "Estimated fetal weight [Mass] by US",
    spanishDisplay: "Peso fetal estimado (PFE) por ecografía",
    aliases: ["PFE", "estimated fetal weight", "peso fetal estimado", "EFW"],
    component: "Estimated fetal weight",
    system: "US",
    scale: "Qn",
  },
  {
    code: "18185-9",
    display: "Gestational age",
    spanishDisplay: "Edad gestacional",
    aliases: ["edad gestacional", "gestational age", "EG", "EGA"],
    component: "Gestational age",
    system: "Patient",
    scale: "Qn",
  },
  {
    code: "33067-6",
    display: "Amniotic fluid index [Length] by US",
    spanishDisplay: "Índice de líquido amniótico (ILA) por ecografía",
    aliases: ["ILA", "amniotic fluid index", "indice de liquido amniotico"],
    component: "Amniotic fluid index",
    system: "US",
    scale: "Qn",
  },
];

export function searchLoinc(query: string, limit = 8): LoincEntry[] {
  const q = query.toLowerCase().trim();
  if (!q) return CHILE_LOINC_SUBSET.slice(0, limit);
  const scored = CHILE_LOINC_SUBSET.map((entry) => {
    const haystack =
      `${entry.code} ${entry.display} ${entry.spanishDisplay} ${entry.aliases.join(" ")} ${entry.component}`.toLowerCase();
    let score = 0;
    if (entry.code === q) score += 100;
    if (entry.component.toLowerCase().includes(q)) score += 40;
    if (entry.spanishDisplay.toLowerCase().includes(q)) score += 30;
    if (entry.display.toLowerCase().includes(q)) score += 20;
    if (entry.aliases.some((a) => a.toLowerCase().includes(q))) score += 25;
    if (haystack.includes(q)) score += 10;
    return { entry, score };
  });
  scored.sort((a, b) => b.score - a.score);
  return scored
    .filter((s) => s.score > 0)
    .slice(0, limit)
    .map((s) => s.entry);
}

export function searchObstetricLoinc(query: string, limit = 8): LoincEntry[] {
  const q = query.toLowerCase().trim();
  if (!q) return OBSTETRIC_LOINC_SUBSET.slice(0, limit);
  const scored = OBSTETRIC_LOINC_SUBSET.map((entry) => {
    const haystack =
      `${entry.code} ${entry.display} ${entry.spanishDisplay} ${entry.aliases.join(" ")} ${entry.component}`.toLowerCase();
    let score = 0;
    if (entry.code === q) score += 100;
    if (entry.component.toLowerCase().includes(q)) score += 40;
    if (entry.spanishDisplay.toLowerCase().includes(q)) score += 30;
    if (entry.display.toLowerCase().includes(q)) score += 20;
    if (entry.aliases.some((a) => a.toLowerCase().includes(q))) score += 25;
    if (haystack.includes(q)) score += 10;
    return { entry, score };
  });
  scored.sort((a, b) => b.score - a.score);
  return scored
    .filter((s) => s.score > 0)
    .slice(0, limit)
    .map((s) => s.entry);
}
