/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GuardianRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "grantGuardianship"
      | "guardians"
      | "identityRegistry"
      | "isGuardian"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "GuardianshipGranted"): EventFragment;

  encodeFunctionData(
    functionFragment: "grantGuardianship",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "guardians",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isGuardian",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "grantGuardianship",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "guardians", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isGuardian", data: BytesLike): Result;
}

export namespace GuardianshipGrantedEvent {
  export type InputTuple = [
    patient: AddressLike,
    guardian: AddressLike,
    certifier: AddressLike
  ];
  export type OutputTuple = [
    patient: string,
    guardian: string,
    certifier: string
  ];
  export interface OutputObject {
    patient: string;
    guardian: string;
    certifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GuardianRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): GuardianRegistry;
  waitForDeployment(): Promise<this>;

  interface: GuardianRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  grantGuardianship: TypedContractMethod<
    [
      patient: AddressLike,
      guardian: AddressLike,
      gType: BigNumberish,
      legalDocHash: BytesLike,
      validUntil: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  guardians: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, bigint, string, bigint, boolean] & {
        guardian: string;
        certifier: string;
        gType: bigint;
        legalDocHash: string;
        validUntil: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  isGuardian: TypedContractMethod<
    [patient: AddressLike, guardian: AddressLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "grantGuardianship"
  ): TypedContractMethod<
    [
      patient: AddressLike,
      guardian: AddressLike,
      gType: BigNumberish,
      legalDocHash: BytesLike,
      validUntil: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "guardians"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, bigint, string, bigint, boolean] & {
        guardian: string;
        certifier: string;
        gType: bigint;
        legalDocHash: string;
        validUntil: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isGuardian"
  ): TypedContractMethod<
    [patient: AddressLike, guardian: AddressLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "GuardianshipGranted"
  ): TypedContractEvent<
    GuardianshipGrantedEvent.InputTuple,
    GuardianshipGrantedEvent.OutputTuple,
    GuardianshipGrantedEvent.OutputObject
  >;

  filters: {
    "GuardianshipGranted(address,address,address)": TypedContractEvent<
      GuardianshipGrantedEvent.InputTuple,
      GuardianshipGrantedEvent.OutputTuple,
      GuardianshipGrantedEvent.OutputObject
    >;
    GuardianshipGranted: TypedContractEvent<
      GuardianshipGrantedEvent.InputTuple,
      GuardianshipGrantedEvent.OutputTuple,
      GuardianshipGrantedEvent.OutputObject
    >;
  };
}
