/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IdentityRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "entities"
      | "getRole"
      | "isVerified"
      | "registerEntity"
      | "verifyEntity"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "EntityRegistered" | "EntityVerified"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "entities",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerified",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerEntity",
    values: [AddressLike, BigNumberish, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyEntity",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "entities", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isVerified", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerEntity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyEntity",
    data: BytesLike
  ): Result;
}

export namespace EntityRegisteredEvent {
  export type InputTuple = [wallet: AddressLike, role: BigNumberish];
  export type OutputTuple = [wallet: string, role: bigint];
  export interface OutputObject {
    wallet: string;
    role: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EntityVerifiedEvent {
  export type InputTuple = [wallet: AddressLike];
  export type OutputTuple = [wallet: string];
  export interface OutputObject {
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IdentityRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IdentityRegistry;
  waitForDeployment(): Promise<this>;

  interface: IdentityRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  entities: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, string, string, boolean] & {
        wallet: string;
        role: bigint;
        specialty: string;
        institution: string;
        verified: boolean;
      }
    ],
    "view"
  >;

  getRole: TypedContractMethod<[wallet: AddressLike], [bigint], "view">;

  isVerified: TypedContractMethod<[wallet: AddressLike], [boolean], "view">;

  registerEntity: TypedContractMethod<
    [
      wallet: AddressLike,
      role: BigNumberish,
      specialty: string,
      institution: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  verifyEntity: TypedContractMethod<
    [wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "entities"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, string, string, boolean] & {
        wallet: string;
        role: bigint;
        specialty: string;
        institution: string;
        verified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRole"
  ): TypedContractMethod<[wallet: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isVerified"
  ): TypedContractMethod<[wallet: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerEntity"
  ): TypedContractMethod<
    [
      wallet: AddressLike,
      role: BigNumberish,
      specialty: string,
      institution: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyEntity"
  ): TypedContractMethod<[wallet: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "EntityRegistered"
  ): TypedContractEvent<
    EntityRegisteredEvent.InputTuple,
    EntityRegisteredEvent.OutputTuple,
    EntityRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "EntityVerified"
  ): TypedContractEvent<
    EntityVerifiedEvent.InputTuple,
    EntityVerifiedEvent.OutputTuple,
    EntityVerifiedEvent.OutputObject
  >;

  filters: {
    "EntityRegistered(address,uint8)": TypedContractEvent<
      EntityRegisteredEvent.InputTuple,
      EntityRegisteredEvent.OutputTuple,
      EntityRegisteredEvent.OutputObject
    >;
    EntityRegistered: TypedContractEvent<
      EntityRegisteredEvent.InputTuple,
      EntityRegisteredEvent.OutputTuple,
      EntityRegisteredEvent.OutputObject
    >;

    "EntityVerified(address)": TypedContractEvent<
      EntityVerifiedEvent.InputTuple,
      EntityVerifiedEvent.OutputTuple,
      EntityVerifiedEvent.OutputObject
    >;
    EntityVerified: TypedContractEvent<
      EntityVerifiedEvent.InputTuple,
      EntityVerifiedEvent.OutputTuple,
      EntityVerifiedEvent.OutputObject
    >;
  };
}
