/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface HealthProofProtocolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "auditTrail"
      | "canAccessDocument"
      | "documentRegistry"
      | "grantAccess"
      | "logDocumentAccess"
      | "permissionManager"
      | "registerMedicalDocument"
      | "revokeAccess"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "auditTrail",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canAccessDocument",
    values: [AddressLike, AddressLike, BytesLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "documentRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantAccess",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "logDocumentAccess",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "permissionManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerMedicalDocument",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      BytesLike,
      BytesLike,
      string,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAccess",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "auditTrail", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "canAccessDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "documentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logDocumentAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "permissionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerMedicalDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAccess",
    data: BytesLike
  ): Result;
}

export interface HealthProofProtocol extends BaseContract {
  connect(runner?: ContractRunner | null): HealthProofProtocol;
  waitForDeployment(): Promise<this>;

  interface: HealthProofProtocolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  auditTrail: TypedContractMethod<[], [string], "view">;

  canAccessDocument: TypedContractMethod<
    [
      patient: AddressLike,
      requester: AddressLike,
      documentId: BytesLike,
      documentType: BytesLike,
      institution: AddressLike
    ],
    [boolean],
    "view"
  >;

  documentRegistry: TypedContractMethod<[], [string], "view">;

  grantAccess: TypedContractMethod<
    [
      patient: AddressLike,
      grantee: AddressLike,
      scope: BigNumberish,
      resourceId: BytesLike,
      expiresAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  logDocumentAccess: TypedContractMethod<
    [patient: AddressLike, documentId: BytesLike],
    [void],
    "nonpayable"
  >;

  permissionManager: TypedContractMethod<[], [string], "view">;

  registerMedicalDocument: TypedContractMethod<
    [
      documentId: BytesLike,
      patient: AddressLike,
      institution: AddressLike,
      documentType: BytesLike,
      clinicalHash: BytesLike,
      cid: string,
      standard: BytesLike,
      classification: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  revokeAccess: TypedContractMethod<
    [patient: AddressLike, grantee: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "auditTrail"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "canAccessDocument"
  ): TypedContractMethod<
    [
      patient: AddressLike,
      requester: AddressLike,
      documentId: BytesLike,
      documentType: BytesLike,
      institution: AddressLike
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "documentRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "grantAccess"
  ): TypedContractMethod<
    [
      patient: AddressLike,
      grantee: AddressLike,
      scope: BigNumberish,
      resourceId: BytesLike,
      expiresAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "logDocumentAccess"
  ): TypedContractMethod<
    [patient: AddressLike, documentId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "permissionManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerMedicalDocument"
  ): TypedContractMethod<
    [
      documentId: BytesLike,
      patient: AddressLike,
      institution: AddressLike,
      documentType: BytesLike,
      clinicalHash: BytesLike,
      cid: string,
      standard: BytesLike,
      classification: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeAccess"
  ): TypedContractMethod<
    [patient: AddressLike, grantee: AddressLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
