/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface HealthProofKernelInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "getModule"
      | "governance"
      | "guardian"
      | "modules"
      | "pauseProtocol"
      | "protocolPaused"
      | "registerModule"
      | "resumeProtocol"
      | "upgradeModule"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ModuleRegistered"
      | "ModuleUpdated"
      | "ProtocolPaused"
      | "ProtocolResumed"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getModule",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "governance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "guardian", values?: undefined): string;
  encodeFunctionData(functionFragment: "modules", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "pauseProtocol",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerModule",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resumeProtocol",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeModule",
    values: [BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getModule", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "governance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "guardian", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "modules", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseProtocol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resumeProtocol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeModule",
    data: BytesLike
  ): Result;
}

export namespace ModuleRegisteredEvent {
  export type InputTuple = [moduleId: BytesLike, module: AddressLike];
  export type OutputTuple = [moduleId: string, module: string];
  export interface OutputObject {
    moduleId: string;
    module: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ModuleUpdatedEvent {
  export type InputTuple = [moduleId: BytesLike, module: AddressLike];
  export type OutputTuple = [moduleId: string, module: string];
  export interface OutputObject {
    moduleId: string;
    module: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolPausedEvent {
  export type InputTuple = [triggeredBy: AddressLike];
  export type OutputTuple = [triggeredBy: string];
  export interface OutputObject {
    triggeredBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolResumedEvent {
  export type InputTuple = [triggeredBy: AddressLike];
  export type OutputTuple = [triggeredBy: string];
  export interface OutputObject {
    triggeredBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HealthProofKernel extends BaseContract {
  connect(runner?: ContractRunner | null): HealthProofKernel;
  waitForDeployment(): Promise<this>;

  interface: HealthProofKernelInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  getModule: TypedContractMethod<[moduleId: BytesLike], [string], "view">;

  governance: TypedContractMethod<[], [string], "view">;

  guardian: TypedContractMethod<[], [string], "view">;

  modules: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  pauseProtocol: TypedContractMethod<[], [void], "nonpayable">;

  protocolPaused: TypedContractMethod<[], [boolean], "view">;

  registerModule: TypedContractMethod<
    [moduleId: BytesLike, moduleAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  resumeProtocol: TypedContractMethod<[], [void], "nonpayable">;

  upgradeModule: TypedContractMethod<
    [moduleId: BytesLike, newAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getModule"
  ): TypedContractMethod<[moduleId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "governance"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "guardian"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "modules"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "pauseProtocol"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "protocolPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerModule"
  ): TypedContractMethod<
    [moduleId: BytesLike, moduleAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resumeProtocol"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeModule"
  ): TypedContractMethod<
    [moduleId: BytesLike, newAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ModuleRegistered"
  ): TypedContractEvent<
    ModuleRegisteredEvent.InputTuple,
    ModuleRegisteredEvent.OutputTuple,
    ModuleRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ModuleUpdated"
  ): TypedContractEvent<
    ModuleUpdatedEvent.InputTuple,
    ModuleUpdatedEvent.OutputTuple,
    ModuleUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolPaused"
  ): TypedContractEvent<
    ProtocolPausedEvent.InputTuple,
    ProtocolPausedEvent.OutputTuple,
    ProtocolPausedEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolResumed"
  ): TypedContractEvent<
    ProtocolResumedEvent.InputTuple,
    ProtocolResumedEvent.OutputTuple,
    ProtocolResumedEvent.OutputObject
  >;

  filters: {
    "ModuleRegistered(bytes32,address)": TypedContractEvent<
      ModuleRegisteredEvent.InputTuple,
      ModuleRegisteredEvent.OutputTuple,
      ModuleRegisteredEvent.OutputObject
    >;
    ModuleRegistered: TypedContractEvent<
      ModuleRegisteredEvent.InputTuple,
      ModuleRegisteredEvent.OutputTuple,
      ModuleRegisteredEvent.OutputObject
    >;

    "ModuleUpdated(bytes32,address)": TypedContractEvent<
      ModuleUpdatedEvent.InputTuple,
      ModuleUpdatedEvent.OutputTuple,
      ModuleUpdatedEvent.OutputObject
    >;
    ModuleUpdated: TypedContractEvent<
      ModuleUpdatedEvent.InputTuple,
      ModuleUpdatedEvent.OutputTuple,
      ModuleUpdatedEvent.OutputObject
    >;

    "ProtocolPaused(address)": TypedContractEvent<
      ProtocolPausedEvent.InputTuple,
      ProtocolPausedEvent.OutputTuple,
      ProtocolPausedEvent.OutputObject
    >;
    ProtocolPaused: TypedContractEvent<
      ProtocolPausedEvent.InputTuple,
      ProtocolPausedEvent.OutputTuple,
      ProtocolPausedEvent.OutputObject
    >;

    "ProtocolResumed(address)": TypedContractEvent<
      ProtocolResumedEvent.InputTuple,
      ProtocolResumedEvent.OutputTuple,
      ProtocolResumedEvent.OutputObject
    >;
    ProtocolResumed: TypedContractEvent<
      ProtocolResumedEvent.InputTuple,
      ProtocolResumedEvent.OutputTuple,
      ProtocolResumedEvent.OutputObject
    >;
  };
}
