/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ClinicalEpisodeRegistry__factory } from "./ClinicalEpisodeRegistry__factory";
export { MedicalDocumentRegistry__factory } from "./MedicalDocumentRegistry__factory";
export { MedicalOrderRegistry__factory } from "./MedicalOrderRegistry__factory";
